_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
data_folder:
    value: data
depth_weight:
    value: 0
device:
    value: cuda
dssim_weight:
    value: 0.4
eval_interval:
    value: 500
l1_weight:
    value: 0.8
lr:
    value: 0.001
name:
    value: 3dgs
num_points:
    value: 4096
num_steps:
    value: 1000
output_folder:
    value: outputs
render:
    value:
        tile_size: 16
resize_scale:
    value: 0.3
