name: 3dgs

data_folder: data
resize_scale: 0.35
num_steps: 10000
num_points: 16384  # 2 ** 14
l1_weight: 0.8
dssim_weight: 0.3
depth_weight: 0.1
lr: 1e-3
eval_interval: 1000
output_folder: outputs
device: cuda
render:
  tile_size: 50